---
- name: Configure Kubernetes Dependencies
  hosts: all
  become: yes

  tasks:
    - name: Disable swap
      command: "{{ item }}"
      loop:
        - "swapoff -a"
        - "sysctl -w vm.swappiness=0"
        - "sed -ri 's/.*swap.*/#&/' /etc/fstab"
      ignore_errors: yes

    - name: Disable Ubuntu firewall
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Install containerd
      block:
        - name: Download containerd
          get_url:
            url: "https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz"
            dest: "/tmp/containerd-1.6.6-linux-amd64.tar.gz"

        - name: Extract containerd
          command: "tar Czxvf /usr/local /tmp/containerd-1.6.6-linux-amd64.tar.gz"

        - name: Download containerd service file
          get_url:
            url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
            dest: "/usr/lib/systemd/system/containerd.service"

        - name: Reload systemd
          systemd:
            daemon_reload: yes

        - name: Enable and start containerd
          systemd:
            name: containerd
            enabled: yes
            state: started

      when: not containerd_installed.changed

      register: containerd_installed

    - name: Install runc
      block:
        - name: Download runc
          get_url:
            url: "https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64"
            dest: "/usr/local/sbin/runc"
            mode: "0755"

      when: not runc_installed.changed

      register: runc_installed

    - name: Install CNI plugins
      block:
        - name: Download CNI plugins
          get_url:
            url: "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
            dest: "/tmp/cni-plugins-linux-amd64-v1.1.1.tgz"

        - name: Extract CNI plugins
          command: "tar Cxzvf /opt/cni/bin /tmp/cni-plugins-linux-amd64-v1.1.1.tgz"

      when: not cni_plugins_installed.changed

      register: cni_plugins_installed

    - name: Create containerd config
      copy:
        content: |
          version = 2
          root = "/var/lib/containerd"
        dest: "/etc/containerd/config.toml"

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Load required kernel modules
      block:
        - name: Configure kernel modules
          copy:
            content: |
              overlay
              br_netfilter
            dest: "/etc/modules-load.d/k8s.conf"

        - name: Load kernel modules
          command: "modprobe {{ item }}"
          loop:
            - overlay
            - br_netfilter

      when: not kernel_modules_loaded.changed

      register: kernel_modules_loaded

    - name: Set sysctl parameters
      block:
        - name: Configure sysctl parameters
          sysctl:
            name: "{{ item.key }}"
            value: "{{ item.value }}"
          loop:
            - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
            - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
            - { key: "net.ipv4.ip_forward", value: "1" }

        - name: Apply sysctl parameters
          command: "sysctl --system"

      when: not sysctl_params_set.changed

      register: sysctl_params_set
